[package]
name = "day-06"
version = "0.1.0"
authors = ["Tobias Kohlmaier <tobias.kohlmaier@bearingpoint.com>"]
edition = "2021"

[dependencies]
itertools = "0.10"
tokio = { version = "1", features = ["full"]}
